// <auto-generated />
using System;
using Meaoc_API.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Meaoc_API.Migrations
{
    [DbContext(typeof(MeaocContext))]
    [Migration("20190120120707_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Meaoc_API.Domain.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("DateSent");

                    b.Property<bool>("IsRead");

                    b.Property<int>("RecipientId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "Hello there, how are you today?",
                            DateSent = new DateTime(2019, 1, 20, 14, 7, 7, 459, DateTimeKind.Local).AddTicks(5594),
                            IsRead = false,
                            RecipientId = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Content = "Wait for me. I will be ready in 10 minutes.",
                            DateSent = new DateTime(2019, 1, 20, 14, 7, 7, 461, DateTimeKind.Local).AddTicks(843),
                            IsRead = false,
                            RecipientId = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Content = "It was a pleasure seeing you!",
                            DateSent = new DateTime(2019, 1, 20, 14, 7, 7, 461, DateTimeKind.Local).AddTicks(883),
                            IsRead = false,
                            RecipientId = 3
                        });
                });

            modelBuilder.Entity("Meaoc_API.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "drenski666@gmail.com",
                            FirstName = "Kaloyan",
                            LastName = "Drenski",
                            PasswordHash = new byte[] { 164, 179, 230, 253, 197, 173, 112, 169, 36, 219, 44, 3, 219, 173, 157, 50, 240, 52, 80, 140, 95, 90, 109, 141, 85, 239, 6, 48, 117, 183, 158, 121, 0, 144, 81, 176, 170, 224, 103, 143, 35, 104, 221, 41, 219, 234, 101, 197, 237, 51, 146, 246, 123, 182, 80, 152, 108, 110, 107, 109, 209, 92, 166, 86 },
                            PasswordSalt = new byte[] { 127, 250, 208, 16, 176, 94, 58, 147, 233, 89, 225, 65, 208, 248, 103, 225, 225, 128, 159, 224, 180, 242, 9, 1, 144, 232, 9, 160, 71, 65, 241, 101, 99, 154, 29, 121, 204, 84, 214, 223, 224, 200, 108, 45, 165, 60, 2, 109, 162, 29, 201, 218, 253, 56, 206, 178, 28, 118, 71, 100, 22, 234, 220, 208, 189, 64, 234, 65, 121, 17, 96, 4, 245, 4, 61, 226, 111, 203, 229, 248, 95, 192, 178, 28, 81, 174, 147, 58, 167, 126, 210, 54, 21, 171, 205, 114, 37, 42, 82, 247, 11, 236, 187, 101, 240, 72, 146, 204, 215, 211, 99, 88, 120, 137, 68, 254, 69, 143, 214, 113, 142, 135, 137, 167, 220, 78, 131, 106 },
                            Username = "kdrenski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bill@microsoft.com",
                            FirstName = "Bill",
                            LastName = "Gates",
                            PasswordHash = new byte[] { 73, 178, 79, 140, 203, 225, 127, 72, 127, 52, 203, 95, 54, 56, 148, 205, 29, 249, 255, 38, 7, 127, 115, 13, 76, 85, 22, 144, 100, 221, 187, 240, 112, 15, 151, 107, 121, 227, 106, 145, 236, 173, 82, 57, 75, 138, 213, 82, 64, 40, 179, 54, 142, 245, 182, 164, 73, 142, 50, 204, 32, 5, 101, 91 },
                            PasswordSalt = new byte[] { 45, 61, 170, 42, 135, 176, 65, 45, 30, 10, 6, 180, 117, 5, 228, 94, 176, 156, 93, 69, 111, 24, 206, 225, 235, 255, 56, 121, 153, 153, 25, 192, 115, 138, 2, 124, 6, 178, 101, 196, 17, 71, 170, 241, 40, 181, 168, 242, 53, 181, 142, 106, 130, 15, 133, 126, 110, 15, 164, 199, 207, 252, 186, 132, 28, 203, 147, 143, 61, 200, 3, 69, 188, 112, 47, 1, 145, 156, 210, 121, 72, 73, 229, 187, 31, 1, 200, 128, 196, 39, 81, 147, 42, 94, 106, 93, 137, 142, 226, 183, 198, 237, 173, 242, 100, 41, 74, 103, 56, 165, 239, 102, 82, 41, 236, 30, 72, 0, 54, 34, 142, 86, 255, 250, 197, 218, 15, 167 },
                            Username = "bill"
                        },
                        new
                        {
                            Id = 3,
                            Email = "elon@tesla.com",
                            FirstName = "Elon",
                            LastName = "Musk",
                            PasswordHash = new byte[] { 47, 147, 59, 135, 253, 226, 96, 237, 182, 4, 148, 224, 140, 208, 212, 20, 241, 182, 251, 156, 27, 28, 59, 217, 182, 247, 177, 103, 15, 84, 170, 61, 127, 195, 45, 234, 42, 168, 25, 129, 247, 19, 36, 122, 68, 173, 144, 177, 251, 23, 145, 102, 98, 15, 117, 105, 181, 226, 188, 107, 129, 13, 48, 25 },
                            PasswordSalt = new byte[] { 138, 28, 194, 37, 38, 179, 182, 64, 8, 128, 217, 24, 56, 190, 95, 155, 181, 2, 102, 130, 213, 13, 105, 255, 216, 147, 208, 231, 74, 79, 151, 228, 139, 47, 4, 219, 186, 61, 112, 186, 113, 81, 46, 246, 79, 46, 56, 124, 187, 138, 233, 188, 241, 56, 88, 250, 130, 42, 161, 17, 86, 155, 29, 240, 161, 192, 252, 137, 6, 159, 225, 64, 194, 126, 56, 77, 177, 143, 108, 192, 117, 221, 59, 154, 0, 106, 223, 211, 131, 6, 146, 224, 237, 15, 175, 87, 4, 34, 34, 51, 51, 4, 101, 95, 19, 22, 12, 243, 45, 71, 17, 174, 70, 244, 217, 84, 43, 211, 250, 142, 215, 173, 149, 83, 241, 114, 221, 16 },
                            Username = "elon"
                        });
                });

            modelBuilder.Entity("Meaoc_API.Domain.Models.Message", b =>
                {
                    b.HasOne("Meaoc_API.Domain.Models.User", "Author")
                        .WithMany("SentMessages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Meaoc_API.Domain.Models.User", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
